version: '3.8'

services:
  mysql:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASWORD
      - MYSQL_DATABASE=hossaikdb
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  app:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 3000:3000